# -*- coding: utf-8 -*-
"""ترجمة

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zu3jgF3icXFp8peJtYyJoLylQdGNbtQN

#**nstall googletrans library**
"""

pip install googletrans==4.0.0-rc1

"""
#**nstall NLTK library**"""

pip install nltk

"""#import

"""

import nltk
from nltk import word_tokenize, sent_tokenize
from googletrans import Translator
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

"""# List of translation grammars

"""

#grammar = nltk.CFG.fromstring("""
    #S -> NP VP
    #NP -> Det N | Det N PP | 'I'
    #VP -> V NP | VP PP
    #PP -> P NP
    #Det -> 'the' | 'a'
    #N -> 'man' | 'woman' | 'dog' | 'cat'
    #V -> 'saw' | 'chased' | 'bit'
    #P -> 'in' | 'on'
#""")

"""
# Function to translate the sentence 
"""

from googletrans import Translator
## Initialize translator object

"""#Take the text that you want to translate from the user"""

text = input("Enter text to translate: ")

text2=text

"""# Tokenize text into sentences

التي تستخدم لتقسيم النص إلى جمل منفصلة.

كن استخدامها في معالجة اللغة الطبيعية لتحليل النصوص وتطبيقات أخرى مثل
"""

text = nltk.sent_tokenize(text2)

words =word_tokenize(text2)

"""هذه الدالة تستخدم لتحديد أنواع الكلمات في النص"""

#pos_tags = pos_tag(words)

"""## Initialize translator object"""

translator = Translator()

"""# Translate each sentence and print result


"""

from nltk import word_tokenize, sent_tokenize

#text2=text

"""#**Take from the user the language he wants to translate into**"""

dest=input("Enter lan to translate: ")

translated_text = translator.translate(text2, dest)

"""**Finally, the print sentence**
**And the output of the translation**
"""

print(text)
print("Translate to " ,dest)
print(translated_text.text)